const zhAuditEventLabels: Record<string, string> = {
  representative_version_published: "发布代表版本",
  representative_version_activated: "启用代表版本",
  message_received: "收到消息",
  message_answered: "回复消息",
  model_context_assembled: "组装模型上下文",
  model_reply_completed: "完成模型回复",
  intake_started: "开始收集需求",
  intake_submitted: "提交需求",
  material_sent: "发送资料",
  payment_invoice_created: "创建支付账单",
  payment_confirmed: "确认支付",
  payment_refunded: "完成退款",
  handoff_prepared: "准备人工接管",
  handoff_requested: "请求人工接管",
  handoff_resolved: "完成人工接管",
  compute_session_requested: "请求 Compute 会话",
  compute_session_started: "启动 Compute 会话",
  compute_session_heartbeat: "记录 Compute 心跳",
  compute_session_terminated: "终止 Compute 会话",
  sandbox_identity_created: "创建沙箱身份",
  sandbox_lease_started: "启动沙箱租约",
  sandbox_lease_stopped: "停止沙箱租约",
  sandbox_lease_errored: "沙箱租约异常",
  tool_execution_requested: "请求工具执行",
  tool_execution_blocked: "阻止工具执行",
  tool_execution_completed: "完成工具执行",
  approval_requested: "发起审批",
  approval_resolved: "完成审批",
  artifact_stored: "保存产物",
  browser_navigation_recorded: "记录浏览器导航",
  browser_session_closed: "关闭浏览器会话",
  billing_ledger_recorded: "记录计费账本",
  workflow_enqueued: "工作流进入队列",
  workflow_completed: "完成工作流",
  workflow_failed: "工作流失败",
  skill_installed: "安装技能",
  skill_binding_changed: "变更代表绑定",
  skill_update_discovered: "发现候选更新",
  skill_version_adopted: "采纳技能版本",
  skill_version_rejected: "拒绝候选版本",
  skill_version_rolled_back: "回滚技能版本",
  skill_archived: "归档技能",
  skill_restored: "恢复技能",
  skill_update_policy_changed: "变更技能更新策略",
  mcp_binding_changed: "变更 MCP 连接",
  compute_policy_changed: "变更 Compute 策略",
};

export function auditEventLabel(type: string, locale: "zh" | "en") {
  return locale === "zh"
    ? zhAuditEventLabels[type] ?? type
    : type.replaceAll("_", " ");
}
