BEGIN;

ALTER TYPE "CapabilityKind" ADD VALUE IF NOT EXISTS 'BUILTIN';
ALTER TYPE "CapabilityKind" ADD VALUE IF NOT EXISTS 'KNOWLEDGE';
ALTER TYPE "CapabilityKind" ADD VALUE IF NOT EXISTS 'SKILL';

ALTER TABLE "ToolExecution"
  ALTER COLUMN "sessionId" DROP NOT NULL;

COMMIT;
