#!/usr/bin/env bash

set -Eeuo pipefail

STATE_ROOT="${DELEGATE_STATE_ROOT:-/home/ubuntu/delegate/shared}"
ENV_ROOT="${DELEGATE_ENV_ROOT:-${STATE_ROOT}/env}"
MATRIX_ROOT="${STATE_ROOT}/matrix"
STATE_ENV="${ENV_ROOT}/state.env"
HOMESERVER="${MATRIX_ROOT}/homeserver.yaml"
REGISTRATION="${MATRIX_ROOT}/delegate-appservice.yaml"
SYNAPSE_IMAGE="${MATRIX_SYNAPSE_IMAGE:-matrixdotorg/synapse:v1.157.0}"

[[ -f "$STATE_ENV" ]] || {
  echo "Missing generated secret state: $STATE_ENV" >&2
  exit 2
}

set -a
# Generated by prepare-env.mjs with shell-safe JSON quoted values.
source "$STATE_ENV"
set +a

umask 077
mkdir -p "$MATRIX_ROOT"

if [[ ! -f "$HOMESERVER" ]]; then
  echo "Generating Synapse configuration for matrix.bonary.xyz."
  docker run --rm \
    --env SYNAPSE_SERVER_NAME=matrix.bonary.xyz \
    --env SYNAPSE_REPORT_STATS=no \
    --env UID=1000 \
    --env GID=1001 \
    --volume "${MATRIX_ROOT}:/data" \
    "$SYNAPSE_IMAGE" generate
fi

if [[ -f "$REGISTRATION" ]]; then
  grep -Fq "as_token: '${MATRIX_AS_TOKEN}'" "$REGISTRATION" || {
    echo "Existing Matrix Application Service token differs; refusing rotation." >&2
    exit 3
  }
  grep -Fq "hs_token: '${MATRIX_AS_HS_TOKEN}'" "$REGISTRATION" || {
    echo "Existing Matrix homeserver token differs; refusing rotation." >&2
    exit 3
  }
else
  registration_temp="$(mktemp "${REGISTRATION}.tmp.XXXXXX")"
  cat >"$registration_temp" <<EOF
id: 'delegate-matrix-as'
url: http://matrix-bridge:4030
as_token: '${MATRIX_AS_TOKEN}'
hs_token: '${MATRIX_AS_HS_TOKEN}'
sender_localpart: _delegate_as
rate_limited: false
receive_ephemeral: false
inhibit_login: true
namespaces:
  users:
    - exclusive: true
      regex: '^@_delegate_.*:matrix\\.bonary\\.xyz$'
  aliases: []
  rooms: []
EOF
  mv "$registration_temp" "$REGISTRATION"
fi

if ! grep -Fq '/data/delegate-appservice.yaml' "$HOMESERVER"; then
  cat >>"$HOMESERVER" <<'EOF'

# Delegate Application Service registration. The referenced file is persisted
# with the Synapse state and contains bearer credentials.
app_service_config_files:
  - /data/delegate-appservice.yaml
EOF
fi

# The Matrix server name is immutable; the public base URL may be safely
# normalized before first traffic and on subsequent idempotent deploys.
sed -i '/^public_baseurl:/d' "$HOMESERVER"
cat >>"$HOMESERVER" <<'EOF'
public_baseurl: https://matrix.bonary.xyz/
EOF

chmod 600 "$HOMESERVER" "$REGISTRATION"
echo "Synapse configuration is ready."
